### ISSUE TITLE
Guardian ttl

### ISSUE THREAD

**Issue by mdillavou** [bitwalker/conform#96] opened 2016-12-02 20:57 UTC
For configuring guardian's ttl, the configuration expects a tuple in the form of {30, :days}. No matter what I do, conform seems to always turn this into [30, :days], which causes guardian's internal pattern matching to fail. Is there anyway to configure this?

Here's a link to guardian:
https://github.com/ueberauth/guardian#installation

**Comment by bitwalker** [comment] 2016-12-20 05:15
So sorry for the delay in getting back to you, I'm just now turning my attention back to conform to bring it up to speed. Could you update now that I pushed the fix for your other issue and let me know if we still have a problem? If so, if you wouldn't mind sharing your schema and conf (it's ok to elide anything sensitive which isn't relevant), that will help a great deal. Thanks!

**Comment by geofflane** [comment] 2017-01-10 21:19
MASTER currently produces the proper output:
```
    "guardian.Elixir.Guardian.ttl": [
       commented: false,
       datatype: {:integer, :atom},
       default: {30, :days},
       doc: "Provide documentation for guardian.Elixir.Guardian.ttl here.",
       hidden: false,
       to: "guardian.Elixir.Guardian.ttl"
    ],
```

But when you run `mix conform.configure` an error occurs:
```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {30, :days}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/conform/translate.ex:321: Conform.Translate.write_datatype/3
    lib/conform/translate.ex:55: anonymous fn/2 in Conform.Translate.to_conf/1
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/conform.configure.ex:43: Mix.Tasks.Conform.Configure.do_run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Looks like `write_datatype` needs to be updated too?

**Comment by bitwalker** [comment] 2017-02-03 23:36
This should now be fixed in master

**Comment by dpehrson** [comment] 2017-03-10 14:25
@bitwalker Is this actually fixed on master? I'm on 2.3.0 (which appears to be the master HEAD) and get this error when running `mix conform.configure`:

```
./scripts/everest.sh mix conform.configure
** (Protocol.UndefinedError) protocol String.Chars not implemented for {30, :days}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/conform/translate.ex:473: Conform.Translate.write_datatype/3
    lib/conform/translate.ex:62: anonymous fn/2 in Conform.Translate.to_conf/1
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/conform.configure.ex:43: Mix.Tasks.Conform.Configure.do_run/1
    (mix) lib/mix/project.ex:312: Mix.Project.in_project/4
    (elixir) lib/file.ex:1162: File.cd!/2
```

**Comment by bitwalker** [comment] 2017-03-10 18:23
The problem is that this value cannot be represented in the `.conf` format. I suppose the best thing to do here would be to set it to nil, and print a warning about it. The best way to handle values like this is to set them up to take a `:binary` value, and write a transform which parses a string like "30 days" into the tuple desired.

That said, you're right this isn't entirely fixed until I come up with a solution to transforming unrepresentable values into the `.conf`.

**Comment by dpehrson** [comment] 2017-03-10 21:42
@bitwalker Thanks for the reply and all your hard work! My guess is it's the same issue at play in #113 which I also see even on 2.3.0.

I can find no combination of values that work for the values Phoenix expects for the `pubsub` key.

I'll try to use transforms.

**Comment by bitwalker** [comment] 2017-05-18 03:42
Generation of the .conf will no longer be blocked by this issue starting in 2.3.3, but a warning will be printed informing users that the value could not be automatically stringified. It will be up to the user to figure out how to encode such values in the .conf, whether by using a string and transforming it, or using some other mixture of types.

**Closed by bitwalker** 2017-05-18 03:42 UTC
Labels: bug
