### ISSUE TITLE
Logger backends config doesn't work with mix conform.configure

### ISSUE THREAD

**Issue by antipax** [bitwalker/conform#47] opened 2015-10-16 18:04 UTC
While

``` elixir
config :logger, :backends, [
  :console,
  {ExSyslog, :exsyslog_error},
  {ExSyslog, :exsyslog_debug}
]
```

works fine with 1.0.0-pre's mix conform.new, and appears to generate a correct  .schema.exs file:

``` elixir
    "logger.backends": [
      commented: false,
      datatype: [
        list: :atom
      ],
      default: [
        :console,
        "ExSyslog": :exsyslog_error,
        "ExSyslog": :exsyslog_debug
      ],
      doc: "Provide documentation for logger.backends here.",
      hidden: false,
      to: "logger.backends"
    ],
```

, there is a failure when generating a new conf using mix conform.configure:

``` bash
╰─$ mix conform.configure
** (ArgumentError) argument error
    :erlang.atom_to_binary({:ExSyslog, :exsyslog_error}, :utf8)
    lib/conform/translate.ex:275: Conform.Translate.write_datatype/3
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    lib/conform/translate.ex:290: Conform.Translate.write_datatype/3
    lib/conform/translate.ex:55: anonymous fn/2 in Conform.Translate.to_conf/1
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
```

Not sure if this is a dupe of #20, but figured you might want to know since this is probably a very common configuration option for Elixir in production. Thanks for conform and exrm!!! :heart:

**Comment by bitwalker** [comment] 2015-10-17 00:43
Thanks for testing 1.0.0-pre! This is exactly the kind of thing I wanted to catch before going 1.0. I'll take a look when I get home later and get a fix pushed.

**Comment by bradleyd** [comment] 2016-03-10 20:20
any movement on this @bitwalker ?

**Comment by bitwalker** [comment] 2016-03-18 17:28
Sorry I have let this one slip for so long, it's on my TODO list for the next release.

**Comment by martin-langhoff** [comment] 2016-04-16 02:13
AFAICT, this is because Conform cannot handle tuples. Turning your tuple into a list makes Conform happy.

Whether that's a useful workaround ...

@bitwalker -- any hints on how to address this? I don't mind putting in the effort but I'm new around here (you may have heard me say this before :-) ).

**Comment by martin-langhoff** [comment] 2016-04-16 23:04
BTW, this affects usage with cqerl as cqerl wants a list to configure cassandra_nodes list - https://github.com/matehat/cqerl

**Comment by bitwalker** [comment] 2016-06-14 19:39
Yeah I think I know what's going on here, the current set of types don't work well with mixed lists like in your example, I need to think on the best way to express that, in both the schema and the parser

**Comment by oadeojo** [comment] 2016-08-31 19:32
I am experiencing a similar issue with creating an exrm release with exsyslog in my app. @martin-langhoff did changing the tuple to a list work for you?

**Comment by bitwalker** [comment] 2017-02-03 23:27
This should now be fixed in master, I've cleaned up the handling of mixed types in lists, nested lists, and other combinations of primitive types quite a bit, so it should work much more intuitively now - the same applies to generating schemas, so if you want to see what a datatype should look like, generate a config and see how it outputs it.

**Closed** 2017-02-03 23:26 UTC

**Comment by AlexRiedler** [comment] 2017-03-02 21:43
@bitwalker I think I may have found another case of this I am running v2.2.2;

I am using KafkaEx hex which has a format of:

(config.exs)
```
config :kafka_ex,
  # a list of brokers to connect to in {"HOST", port} format
  brokers: [
    {"localhost", 9092},
  ]
```

which goes to:

(schema.exs)
```
    "kafka_ex.brokers": [
      commented: false,
      datatype: [
        list: {:binary, :integer}
      ],
      default: [
        {"localhost", 9092}
      ],
      doc: "Provide documentation for kafka_ex.brokers here.",
      hidden: false,
      to: "kafka_ex.brokers"
    ],
```

and the error is this on conform.configure:

```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {"localhost", 9092}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/conform/translate.ex:479: Conform.Translate.write_datatype/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/conform/translate.ex:463: Conform.Translate.write_datatype/3
    lib/conform/translate.ex:61: anonymous fn/2 in Conform.Translate.to_conf/1
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/conform.configure.ex:43: Mix.Tasks.Conform.Configure.do_run/1
```

And removing the default resolves the issue...

**Comment by meinac** [comment] 2017-05-25 15:32
I've encountered with the similar issue which @AlexRiedler faced before while using `kafka_ex` library and solved by using transforms. The problem is, `kafka_ex` is waiting for a list of tuples which consist of binary and integer pairs. But I think there is no way to handle list of tuples in conform.
But if you use `ip` data type it will almost lead you to solution. I say almost because `ip` datatype consist of binary binary tuple but `kafka_ex` waits binary integer tuple so what I did was, I used transforms to transform list of binary binary tuples to list of binary integer tuples like so:

```elixir
transforms: [
    "kafka_ex.brokers": fn (conf) ->
      case Conform.Conf.get(conf, "kafka_ex.brokers") do
        [{_conf, conf_list}] -> Enum.map(conf_list, fn ({host, port}) -> {host, String.to_integer(port)} end)
        _ -> nil
      end
    end
  ],
```

**Comment by bitwalker** [comment] 2017-06-22 18:35
Conform now warns when generating configs that have unencodable types (such as a tuple like that). It will still generate the .conf, but it will have an empty value for that setting. The key here is to do something along the lines of @meinac's solution - choose a type that you can parse easily, and use a transform to convert it into the type you actually need.
