### ISSUE TITLE
Elixir 1.5.0 - erlang error: {:badrecord, :elixir_erl}

### ISSUE THREAD

**Issue by pgrunwald** [bitwalker/conform#131] opened 2017-07-26 10:10 UTC
### Environment

Operating system: macOS 10.12.5 (16F73) / Darwin 16.6.0
Erlang/OTP 20.0
Elixir 1.5.0 and 1.4.4
Conform 2.4.0

### Current behavior

After upgrading to Elixir 1.5.0, I encounter the following when creating a release and running commands:

```
$> MIX_ENV=release mix release
...
==> Release successfully built!
    You can run it in one of the following ways:
      Interactive: _build/release/rel/myapp/bin/myapp console
      Foreground: _build/release/rel/myapp/bin/myapp foreground
      Daemon: _build/release/rel/myapp/bin/myapp start
$> CONFORM_CONF_PATH=... _build/release/rel/myapp/bin/myapp console
** (ErlangError) erlang error: {:badrecord, :elixir_erl}
    (elixir) src/elixir_erl_var.erl:134: :elixir_erl_var.load_binding/2
    (elixir) lib/code.ex:207: Code.eval_quoted/3
    (conform) lib/conform/schema.ex:98: Conform.Schema.parse/1
    (conform) lib/conform/schema.ex:118: Conform.Schema.parse!/1
    (conform) lib/conform/schema.ex:132: Conform.Schema.load!/1
    (conform) lib/conform.ex:95: Conform.process/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

I can confirm everything is working as expected with Elixir 1.4.4, the only change is the Elixir version. I ran `mix do deps.clean --all, deps.get` before generating a release.

**Comment by bitwalker** [comment] 2017-07-26 13:11
That's strange - I'll update to 1.5 today and take a look.

**Comment by bitwalker** [comment] 2017-07-26 13:24
I can't reproduce locally on master - what version of Conform are you seeing this with?

**Comment by bitwalker** [comment] 2017-07-26 13:57
I wasn't clear in my question, but could you confirm the version stored in `mix.lock`?

**Comment by pgrunwald** [comment] 2017-07-26 13:59
@bitwalker, here is the line for `conform` in my `mix.lock`:

```
  ...
  "conform": {:hex, :conform, "2.4.0", "09ced3c81630885ecd6fb1ca696f3ca58ba4d705e51dc4bab2620c304ea0f9c9", [:mix], [{:neotoma, "~> 1.7.3", [hex: :neotoma, repo: "hexpm", optional: false]}], "hexpm"},
  ...
```

**Comment by pgrunwald** [comment] 2017-07-26 14:02
@bitwalker, there is also a related issue here: https://github.com/elixir-lang/elixir/issues/6365. The solution suggested by @lachezar doesn't seem relevant in this case.

**Comment by pgrunwald** [comment] 2017-07-26 14:05
@bitwalker, additionally, I am using `distillery` for release packaging. I'm not sure if that would affect anything. Here is the line for distillery in my `mix.lock`:

```
  ...
  "distillery": {:hex, :distillery, "1.4.1", "546d851bf27ae8fe0727e10e4fc4e146ad836eecee138263a60431e688044ed3", [:mix], []},
  ...
```

**Comment by lachezar** [comment] 2017-07-26 14:23
I think the problem stems from the fact that the [conform escript](https://github.com/bitwalker/conform/blob/master/priv/bin/conform) was built using elixir 1.4.X and you are trying to run your OTP release with 1.5 ERTS. I did a fork (as a temp solution) and recompiled the escript and it worked - https://github.com/lachezar/conform/tree/elixir-1.5.0

**Comment by pgrunwald** [comment] 2017-07-26 14:35
@lachezar, apologies, I misinterpreted what you meant in the other thread, that makes sense.

**Comment by bitwalker** [comment] 2017-07-26 15:43
I've pushed a new tag, 2.5.0, containing the fix for this. I've tested across various combinations of OTP 19.3/20 and Elixir 1.4.5/1.5.0 with success. I'll push a new release to hex shortly.

**Closed by bitwalker** 2017-07-26 15:43 UTC
