### ISSUE TITLE
Support for lists in config.exs

### ISSUE THREAD

**Issue by gerred** [bitwalker/conform#20] opened 2015-04-27 18:41 UTC
I have a config.exs value that is a list. When I go to make a release, I get a failure in conform.effective. I'm not sure if I'm intended to be able to use lists in a config, or how that would end up looking in my ops conf file when generating an exrm release.

If this is intended behaviour, maybe a more useful warning? If not, I'm happy to help put together a PR to fix this.

**Comment by bitwalker** [comment] 2015-04-28 15:08
It's definitely supported, could you paste the error? I can help you track it down.

**Comment by gerred** [comment] 2015-04-28 15:19
Sure! I'll repro and post. I was getting an Enum.reduce exception in Translate, but the particular branch I was working on is at home. I'll update in a bit.

**Comment by bitwalker** [comment] 2015-04-28 15:45
@gerred Awesome thanks! I'd guess there is a missing test case somewhere that would've exposed this earlier. I'm thinking it's a bug specific to conform.effective though, not the actual schema processing, since I know we have tests for that.

**Comment by marcelog** [comment] 2015-05-05 19:27
Hello,

I think I'm also affected by this, trying with this config.exs file:
```elixir
use Mix.Config

config :ex_sms,
  sublist: [
    [
      opt1: "val1",
      opt2: "opt2"
    ],
    [
      opt1: "val1",
      opt2: "opt2"
    ]
  ]
```

The schema file generated is:
```elixir
[
  mappings: [
    "ex_sms.sublist": [
      doc: "Provide documentation for ex_sms.sublist here.",
      to: "ex_sms.sublist",
      datatype: [
        list: [
          list: :binary
        ]
      ],
      default: [
        [opt1: "val1", opt2: "opt2"],
        [opt1: "val1", opt2: "opt2"]
      ]
    ]
  ],
  translations: [
  ]
]
```

And the error I get is:
```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:opt1, "val1"}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    lib/conform/translate.ex:254: Conform.Translate.write_datatype/3
    (elixir) lib/enum.ex:1003: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1345: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1003: Enum.map/2
    lib/conform/translate.ex:248: Conform.Translate.write_datatype/3
    (elixir) lib/enum.ex:1003: anonymous fn/3 in Enum.map/2
```

I'm using exrm 0.15.3 which pulls conform 0.13.0

**Comment by c-rack** [comment] 2015-08-14 07:24
We are running into a similar problem here: https://github.com/c-rack/quantum-elixir/issues/15
There is a small test project to reproduce this issue:
https://github.com/alPacino/quantum-elixir-test

Stack trace is (abbreviated):
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for ...
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/enum.ex:1398: Enum.reduce/3
    (conform) lib/conform/translate.ex:66: Conform.Translate.to_config/3
    (conform) lib/conform.ex:91: Conform.process/1
```

**Comment by bitwalker** [comment] 2015-08-14 15:06
I'll look into it this morning everyone, thanks @c-rack for the test case!

**Comment by bitwalker** [comment] 2015-08-17 17:43
@marcelog I've pushed some changes/fixes to master, including support for `list: [list: _]` types. So to accomplish what you wanted, you'd use the following schema/config/conf:

```elixir
# config.exs
use Mix.Config

config :ex_sms,
  sublist: [[opt1: "val1", opt2: "opt2"], [opt1: "val1", opt2: "opt2"]]
```

```elixir
# schema
[
  mappings: [
    "ex_sms.sublist": [
      doc: "Provide documentation for ex_sms.sublist here.",
      to: "ex_sms.sublist",
      datatype: [
        list: [list: {:atom, :binary}]
      ],
      default: [
        [opt1: "val1", opt2: "opt2"],
        [opt1: "val1", opt2: "opt2"]
      ]
    ]
  ],
  translations: [
  ]
]
```

```
# conf
ex_sms.sublist = [opt1 = val1, opt2 = "val two"], [opt1 = val3, opt2 = val-4]
```

Which would produce the following effective configuration:

```
[ex_sms: [sublist: [[opt1: "val1", opt2: "val two"],
   [opt1: "val3", opt2: "val-4"]]]]
```

This is working in master, but I haven't yet released an update on hex. Please test with it and let me know what issues you encounter, if any.

**Comment by bitwalker** [comment] 2015-08-17 17:48
@c-rack Your issue should also be resolved on master as well

**Comment by marcelog** [comment] 2015-08-17 21:35
Hi @bitwalker,

Thank you for looking into this!

It seems *that* was fixed :) But there's another issue when deep nesting config values, like:
```elixir
config :ex_sms,
  sublist: [
    [
      opt1: "val1",
      opt2: "opt2"
    ],
    [
      opt1: "val1",
      opt2: "opt2"
    ],
    [
      opt1: "val1",
      opt2: 1,
      opt3: [
        opt1: ModuleName,
        opt2: :val2,
        opt3: 3
      ]
    ]
  ]
```

```mix conform.configure``` yields:
```elixir
** (ArgumentError) argument error
    (stdlib) :unicode.characters_to_binary([opt1: ModuleName, opt2: :val2, opt3: 3])
    (elixir) lib/list.ex:555: List.to_string/1
    lib/conform/translate.ex:483: Conform.Translate.write_datatype/3
    lib/conform/translate.ex:486: Conform.Translate.write_datatype/3
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    lib/conform/translate.ex:472: anonymous fn/3 in Conform.Translate.write_datatype/3
```

Am I using it in an unexpected (as in unintended) way? Do you have any suggestions for handling this kind of configuration?

Thanks for your time!

**Comment by bitwalker** [comment] 2015-08-17 23:09
@marcelog I think in this case I'd like to see your real-world config (cleaned up of anything sensitive of course), since that will help me give you recommendations or make changes to conform if needed. Right now conform does not support N-level nested sublists, and I hesitate to add such support given that it complicates both the .conf grammar/parser and conform's internals quite a bit. However, if it looks like there isn't a convenient path to supporting your use case, I would definitely consider adding such support if needed.

I need to revamp the documentation before I push this to hex, so I plan to document the limitations/edge cases, but I want to make sure we've landed in a good place first, so this is good discussion :)

**Comment by marcelog** [comment] 2015-08-18 14:37
Fair enough @bitwalker :) The application in question has a few "workers". These workers listen for tasks coming in through a RabbitMQ queue. The N-level nested sublists appear here:
```elixir
config :ex_sms,
  # some other application options
  workers: [
    [
     # Specific worker options
      name: "worker1",
      concurrency: 1,
      callback_module: Module1,
      # Specific RabbitMQ queue options
      queue: [
        name: "queue1_name",
        routing_key: "queue1_routing_key",
        with_retry: true,
        auto_delete: false,
        durable: true,
        exclusive: false,
        passive: false
      ]
    ],
    [
      name: "worker2",
      concurrency: 1,
      callback_module: Module2,
      queue: [
        name: "queue2_name",
        routing_key: "queue2_routing_key",
        with_retry: true,
        auto_delete: false,
        durable: true,
        exclusive: false,
        passive: false
      ]
    ],
  ]
]
```

This is defined like this (instead of giving each worker it's own config section) because:

 * The `workers` config key is iterated by a supervisor that will start all the workers.
 * The `queue` config key contains specific configuration for the RabbitMQ queue, and is used by the worker base module (essentially a module that is `use`d by the workers that contains the needed functionality to interact with RabbitMQ and the tasks themselves).
 * All the options outside the `queue` config key (but inside a worker configuration) are specific to the worker in question, avoiding config keys named like `queue_passive`, `queue_auto_delete`, etc.

So perhaps I should give each worker its own configuration section (and get rid of the `workers` section), and maybe "merge" the queue options with the ones that are worker specific. Although this kind of configuration (as it is) doesn't seem *that* unreasonable.

I'd definitely like to know your thoughts on this.

Thanks!

**Comment by bitwalker** [comment] 2017-02-03 23:46
This should now be fixed in master, so I'm going to close it for now. Please feel free to reopen it if there are still related issues.

**Closed by bitwalker** 2017-02-03 23:46 UTC

**Comment by marcelog** [comment] 2017-02-04 15:21
Thank you @bitwalker, great job! 👍
