### ISSUE TITLE
No support for types such as tuples.

### ISSUE THREAD

**Issue by chandradot99** [bitwalker/conform#152] opened 2018-04-11 10:12 UTC
I am working on an application which uses [quantum](https://github.com/quantum-elixir/quantum-core) library and in its configuration we have to do something like this

```
config :my_app, MyApp.Scheduler,
  jobs: [
    send_message: [
      schedule: "* * * * *",
      task: {MyApp, :send_message, []},
    ]
  ]
```

which will generate the following schema
```
    "my_app.Elixir.MyApp.Scheduler.jobs.send_message.schedule": [
      commented: false,
      datatype: :binary,
      default: "* * * * *",
      doc: ".",
      hidden: false,
      to: "my_app.Elixir.MyApp.Scheduler.jobs.send_message.schedule"
    ],
    "my_app.Elixir.MyApp.Scheduler.jobs.send_message.task": [
      commented: false,
      datatype: {:atom, :atom, :binary},
      default: {MyApp, :send_message, []},
      doc: ".",
      hidden: false,
      to: "my_app.Elixir.MyApp.Scheduler.jobs.send_message.task"
    ]

```
with this schema when I am trying to generate `.conf` file, it gives me the following error.

`Unable to stringify my_app.Elixir.MyApp.Scheduler.jobs.send_message.task, unrecognized type {:atom, :atom, :binary}`

Is there some workaround for this issue.

**Comment by vasspilka** [comment] 2018-05-22 09:59
@chandradot99 This is a duplicate of https://github.com/bitwalker/conform/issues/146, if you have questions regarding Transforms let me know

**Comment by vasspilka** [comment] 2018-05-22 10:04
Basically, conform by itself is very limited to the kind of types it supports. But you can use the binary type and create complex configs with that string. I like separating tuples simply with space ` ` and then do something like 
```
        [one, two, three] = String.split(value)
        {one, two, three}
```

**Closed** 2018-05-23 17:39 UTC
